// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialVN.API.Data;

#nullable disable

namespace SocialVN.API.Migrations
{
    [DbContext(typeof(SocialVNDbContext))]
    [Migration("20250414015126_check")]
    partial class check
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SocialVN.API.Models.Domain.Comment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasComment("ID duy nhất của comment (UUID)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Nội dung comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian tạo comment");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("ID bài viết mà comment thuộc về");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian cập nhật comment");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("ID của người tạo comment");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("SocialVN.API.Models.Domain.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian gửi yêu cầu");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("pending")
                        .HasComment("Trạng thái của yêu cầu kết bạn (pending/accepted/declined)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian cập nhật trạng thái yêu cầu");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("RequesterId");

                    b.ToTable("Friendships", (string)null);
                });

            modelBuilder.Entity("SocialVN.API.Models.Domain.Like", b =>
                {
                    b.Property<string>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasComment("ID duy nhất của lượt thích (UUID)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian thực hiện thích bài viết");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("ID bài viết được thích");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian cập nhật lượt thích");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("ID của người thực hiện thích bài viết");

                    b.HasKey("LikeId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes", (string)null);
                });

            modelBuilder.Entity("SocialVN.API.Models.Domain.Post", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasComment("ID duy nhất của bài viết (UUID)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Nội dung bài viết");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian tạo bài viết");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Đường dẫn ảnh của bài viết (nếu có)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian cập nhật bài viết");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("ID của người dùng tạo bài viết");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts", (string)null);
                });

            modelBuilder.Entity("SocialVN.API.Models.Domain.Report", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasComment("ID duy nhất của báo cáo (UUID)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian tạo báo cáo");

                    b.Property<int>("NewFriends")
                        .HasColumnType("int")
                        .HasComment("Số lượng bạn bè mới trong tuần");

                    b.Property<int>("TotalComments")
                        .HasColumnType("int")
                        .HasComment("Tổng số lượt comment trong tuần");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("int")
                        .HasComment("Tổng số lượt thích trong tuần");

                    b.Property<int>("TotalPosts")
                        .HasColumnType("int")
                        .HasComment("Tổng số bài viết trong tuần");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian cập nhật báo cáo");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasComment("ID của người dùng thực hiện báo cáo");

                    b.Property<DateTime>("WeekEnd")
                        .HasColumnType("datetime(6)")
                        .HasComment("Ngày kết thúc của tuần được báo cáo");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("datetime(6)")
                        .HasComment("Ngày bắt đầu của tuần được báo cáo");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("SocialVN.API.Models.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasComment("ID duy nhất của người dùng (UUID)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Đường dẫn ảnh đại diện của người dùng");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("Ngày tháng năm sinh của người dùng");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian tạo tài khoản");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("Email của người dùng");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasComment("Họ và tên đầy đủ của người dùng");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasComment("Địa chỉ nơi sinh sống của người dùng");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("Nghề nghiệp của người dùng");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Mật khẩu được mã hóa");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("user")
                        .HasComment("Vai trò của người dùng");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian cập nhật tài khoản");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SocialVN.API.Models.Domain.Comment", b =>
                {
                    b.HasOne("SocialVN.API.Models.Domain.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialVN.API.Models.Domain.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialVN.API.Models.Domain.Friendship", b =>
                {
                    b.HasOne("SocialVN.API.Models.Domain.User", "Receiver")
                        .WithMany("FriendshipsAsReceiver")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Friendships_Receiver");

                    b.HasOne("SocialVN.API.Models.Domain.User", "Requester")
                        .WithMany("FriendshipsAsRequester")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Friendships_Requester");

                    b.Navigation("Receiver");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("SocialVN.API.Models.Domain.Like", b =>
                {
                    b.HasOne("SocialVN.API.Models.Domain.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialVN.API.Models.Domain.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialVN.API.Models.Domain.Post", b =>
                {
                    b.HasOne("SocialVN.API.Models.Domain.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialVN.API.Models.Domain.Report", b =>
                {
                    b.HasOne("SocialVN.API.Models.Domain.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialVN.API.Models.Domain.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("SocialVN.API.Models.Domain.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FriendshipsAsReceiver");

                    b.Navigation("FriendshipsAsRequester");

                    b.Navigation("Likes");

                    b.Navigation("Posts");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
